# Generated by Django 2.1.7 on 2019-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('unsubscribed_date', models.DateTimeField(verbose_name='Unsubscribed Date')),
            ],
        ),
    ]
